### ISSUE TITLE
crash problem version: 1.6.3

### ISSUE THREAD

**Issue by VojaFTW** [gigaherz/ToolBelt#10]
my game crash while loading mod version 1.6.3 forge 1.12-14.21.0.2375

crash report:
The game crashed whilst initializing game
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate

thanks.

**Comment by gigaherz** [comment]
you'll need a bit of patience: Forge for 1.12 has had some breaking changes recently. I'm waiting for the Recommended Build, which should happen soon, to push an update.

**Comment by VojaFTW** [comment]
ok thanks

**Comment by VojaFTW** [comment]
crash again forge version: 1.12-14.21.1.2387 recommended http://files.minecraftforge.net/ mod version: 1.6.3 it seems error with your mod not with forge.
Becouse error telling me no class found but forge is recommended version, and cannot contain errors.

error:
The game crashed whilst initializing game
Error: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/RegistryDelegate

**Comment by VojaFTW** [comment]
I know why is crashing reason is optifine qhen i see optifine is reason i say myself wtf and now i trying to make optifine works.

**Comment by gigaherz** [comment]
I have released a new version compiled with the latest forge. It should fix the crash.
