### ISSUE TITLE
cant use epic fight mod and tool belt

### ISSUE THREAD

**Issue by DripPee** [gigaherz/ToolBelt#104]
when i had epic fight mod by itself i could click r and go into fighting stand but after downloading toolbelt it dont work anymore,i click r and nothing happens.   Im on 1.12

**Comment by DripPee** [comment]
pls help me

**Comment by gigaherz** [comment]
go to your minecraft controls options, and unassign the R key from toolbelt.
you can change toolbelt to another key.

**Comment by DripPee** [comment]
ty :))))))
