### ISSUE TITLE
configurable slots amount fot toolbelt

### ISSUE THREAD

**Issue by Nika-m** [gigaherz/ToolBelt#107]
I want players to have 5 aviable slots by default when they craft toolbelt

**Comment by Nika-m** [comment]
thanks, figured it out, if anyone needs it, just add nbt in belt.json recipe like this: 
{
  "type": "forge:conditional",
  "recipes": [
    {
      "conditions": [
        {
          "type": "toolbelt:enable_normal_crafting"
        }
      ],
      "recipe": {
        "type": "minecraft:crafting_shaped",
        "pattern": [
          "sls",
          "l l",
          "lil"
        ],
        "key": {
          "s": {
            "item": "minecraft:string"
          },
          "l": {
            "item": "minecraft:leather"
          },
          "i": {
            "item": "minecraft:iron_ingot"
          }
        },
        "result": {
          "item": "toolbelt:belt",
	"nbt": {
            "Size": 4
          }
        }
      }
    }
  ]
}

**Comment by 0xicl33n** [comment]
okay but does this let you use MORE than 9 slots?
