### ISSUE TITLE
[Resource] es_ES/MX translation

### ISSUE THREAD

**Issue by Dorzar** [gigaherz/ToolBelt#11]
//Translate by: Dorzar / VeryHardChamp
//Última actualización: 23/07/2017
item.toolbelt.belt.name=Cinturón para herramientas
item.toolbelt.pouch.name=Bolsa para cinturón
key.toolbelt.open=Swap Tool
key.toolbelt.category=Tool Belt
text.toolbelt.empty=VACIO
text.toolbelt.swap=CAMBIAR
text.toolbelt.insert=INSERTAR
text.toolbelt.extract=EXTRAER
text.toolbelt.tooltip=Mejoras: %s (%s espacios)
text.toolbelt.name=Cinturón para herramientas

**Comment by gigaherz** [comment]
Thanks. I have added them locally and will be present in the next release.
