### ISSUE TITLE
[1.18] Curious update makes belt slot incompatible

### ISSUE THREAD

**Issue by ffuentesm** [gigaherz/ToolBelt#111]
The new curious update curios-forge-1.18.1-5.0.3.0.jar, made the Belt spot incompatible. 

I try to add the tool belt to the curious slot, but it does nothing.

**Comment by gigaherz** [comment]
Thanks for the report! I'll check

**Comment by ffuentesm** [comment]
I also noticed that the new curious Elytra curiouselytra-forge-1.18.1-5.0.0.0.jar, affects other mods too.

**Comment by gigaherz** [comment]
I have nothing to do with Curios, or that other mod so I can't help with the other issue. I can just fix my mod's compatibility with Curios.

**Comment by gigaherz** [comment]
So I have looked into it, and I can't find any issue. I'm able to place the belt in the slot just fine ...

![image](https://user-images.githubusercontent.com/685851/146388176-c4fb71a1-dd6c-4ee8-b26a-7cd6d36c6f37.png)

**Comment by ffuentesm** [comment]
I checked and yes, Curious is not the problem, but curiouselytra-forge-1.18.1-5.0.0.0.jar seems to be causing problems.
I send an Issue report to them, just in case.
