### ISSUE TITLE
Whitelist causes save crash?

### ISSUE THREAD

**Issue by tawniey** [gigaherz/ToolBelt#116]
Was trying to set up the whitelist, but I cannot seem to implement it without getting a crash when loading the save with the changed config. 

`
[general]
	#List of items to force-allow placing in the belt. Takes precedence over blacklist.
	whitelist = [comforts:sleeping_bag_purple, comforts:sleeping_bag_pink, comforts:sleeping_bag_cyan, comforts:sleeping_bag_yellow, comforts:sleeping_bag_red]
	#List of items to disallow from placing in the belt. (whitelist takes precedence)
	blacklist = []
`

I have a feeling that this is because of a syntax error on my side, but I figured I'd raise it as an "issue" so that maybe the config file can be adjusted to give clearer instructions for the syntax? ^^; 
If that's the case, what is the proper delimiter for a whitelist item? Thanks in advance!

**Comment by gigaherz** [comment]
the values have to be double-quoted, like "comforts:sleeping_bag_purple"

**Comment by tawniey** [comment]
Thank you! That was the missing piece. 

If you feel so inclined, a brief example line on the config file could read: 
`#Example: 
#whitelist = ["minecraft:torch", "toolbelt:breakable_needle"]`
Just so other scatterbrains such as myself might not have to trouble you in future. ^^; 

Cheers!
