### ISSUE TITLE
[1.12 request] Re-enable Baubles compatibility, and also use @optional tags to avoid future issues

### ISSUE THREAD

**Issue by PrinceOfAmber** [gigaherz/ToolBelt#12]
As you may know, baubles came out for 1.12 a few hours ago. Of course you had to disable support for this to release for 1.12 because it wasnt out yet.

Hopefully you find time soon to make a new build with baubles support enabled.  

Also if you are interested, there is a way to add optional dependencies, which could avoid future roadblocks.  This is how I stuck it in https://github.com/PrinceOfAmber/Cyclic/blob/78412ce022b1a0592e45c1f0c93494a5d768b6b8/src/main/java/com/lothrazar/cyclicmagic/item/base/BaseCharm.java#L20   As well as the  @Optional.Method(modid = "baubles") tags below.

Just an idea :)

**Comment by gigaherz** [comment]
I know! :D I wanted to finish a new feature first, but I already enabled Baubles locally. ^_^

The reason I had to disable it was simply that I didn't have a working lib to compile with, and I didn't want to assume that the 1.11 API wouldn't change.

Yeah I did have the @Optional.Interface. I didn't seem to need the one for the method though. It saddens me a little that IBauble is still an interface that goes on the Item class and not a capability, but oh well.

**Comment by gr8pefish** [comment]
It should be capability based [soon](https://github.com/Azanor/Baubles/pull/217) :)

**Comment by gigaherz** [comment]
New version 1.7.0 is up on curseforge, and will be available as soon as it's reviewed. Have fun.

**Comment by PrinceOfAmber** [comment]
Sweet good work
