### ISSUE TITLE
Cannot upgrade final tool belt(upgrade 7- slot 9) with Sewing Kit

### ISSUE THREAD

**Issue by RedBeast1959** [gigaherz/ToolBelt#125]
Tool Belt Version: ToolBelt-1.19-1.19.6.jar
Sewing Kit Version: SewingKit-1.19.2-1.6.6.jar
Forge Version: 1.19.2-forge-43.0.7

![2022-08-10_19 23 00](https://user-images.githubusercontent.com/100399264/183880443-81267e66-9101-4319-a8d9-0bac54a9d5ac.png)

When I was upgrading tool belt with sewing table, it stopped at upgrade 6(slot 8). Every stuffs was prepared, and needle was intacted. So I checked with Just Enough Items mod, upgrade 7 recipe was weird like above screenshot: No needle. So I removed the needle but still uncraftable. There must be a problem with recipes code.

**Comment by gigaherz** [comment]
Strange.
It should need the Netherite needle.
I will see why JEI is wrong.

**Comment by gigaherz** [comment]
This was actually a bug in Sewing Kit, not ToolBelt. You will have to update sewing kit to 1.6.9+, which is currently waiting approval at curseforge.

**Comment by dher383** [comment]
Hmm...I have the same problem in 1.18.2
