### ISSUE TITLE
1.19 crash

### ISSUE THREAD

**Issue by Squeetsquib** [gigaherz/ToolBelt#128]
crash when trying to use gui
https://imgur.com/a/fIBRiEr

also crashes when trying to remove item from belt slot.

**Comment by gigaherz** [comment]
Uh what version of the mod are you using? and minecraft? and forge?
can you provide the debug.log file?

**Comment by Squeetsquib** [comment]
mod version: utilitybelt-1.0.1
minecraft version: 1.19 (guessing the issue is that it was built for 1.19.2)
fabric version: 14.9

**Comment by gigaherz** [comment]
Uh this is the wrong issue tracker then. ToolBelt is not UtilityBelt.
