### ISSUE TITLE
Items keep switching places?

### ISSUE THREAD

**Issue by Jetpack-Cat** [gigaherz/ToolBelt#129]
This is really bizarre how it works. It removes the tool from the belt, so when I open the belt back up, now I have to look at each item again to know where everything is located. If I take another item out, it again changes where everything is located in the tool belt.

It should keep everything in the same place, and the tool you're using should still be shown in the belt, to keep everything in the same place. That way, you can quickly switch tools, knowing where they are on the tool belt wheel.

**Comment by gigaherz** [comment]
Yes, that is how ToolBelt works. If you use the swap feature the items will switch places. If you want items to remain in the same place you will have to insert an item back to its slot, and then extract the new one. You may want to make sure the option to show empty slots is turned on, to help with that.
And no, ToolBelt does not keep track of the items that you removed to keep track of their old position, that is just not how it works.
