### ISSUE TITLE
[1.12] When tool belt in baubles it keybind occasionally does not work

### ISSUE THREAD

**Issue by tgstyle** [gigaherz/ToolBelt#13]
I have not been able to track down steps to reproduce yet. It just happens at random so far. Pulling the belt out of baubles and putting it back in fixes it temporarily until it happens again.

**Comment by gigaherz** [comment]
Yep I belive I experienced this while testing, but only the first time I placed it in the belt, so I forgot later. I'll try to reproduce again, but I suspect it's probably a conflict between Baubles, and my "special" synchronization I use to make sure the data is available in multiplayer, for rendering...

**Comment by gigaherz** [comment]
I *hope* v1.7.1 fixes this issue. I haven't been able to reproduce it again...
