### ISSUE TITLE
Epic Fight Weapons On Tool Belt Not Positioned Correctly

### ISSUE THREAD

**Issue by DeshiDesu** [gigaherz/ToolBelt#131]
ToolBelt-1.18.2-1.18.9.jar
EpicFight-18.3.7.jar
Minecraft 1.18.2
Forge 40.2.0

Certain Epic Fight weapons on tool belt are not positioned correctly.
![Screenshot from 2023-01-23 01-16-48](https://user-images.githubusercontent.com/120287925/213978164-3fe25401-1106-4cf5-a082-9697aa32166b.png)
![Screenshot from 2023-01-23 01-17-28](https://user-images.githubusercontent.com/120287925/213978169-084a5b49-0680-4e67-9927-d889a58b34f9.png)

**Comment by gigaherz** [comment]
I can take a look, but I don't know that I'll be able to do much about this. I rely on the display transforms declared in the item model.

**Comment by DeshiDesu** [comment]
Alright

**Comment by DeshiDesu** [comment]
Fixed in latest version
