### ISSUE TITLE
Displayemptyslots configuration change deleted world + visual bug

### ISSUE THREAD

**Issue by Chereskov** [gigaherz/ToolBelt#135]
I made a single configuration change to the Tool Belt on the display empty slots configuration from False to True (link 3). I did not experience any in-game issues until later when I could not feed rabbits (after a significant amount of time) and I exited, closed Minecraft and CurseForge (CF).

I then reloaded CF, deleted that world's backup "Backup 1", and created a backup "Backup 2" for this world version that I just exited. Below is the screenshot of the screen after I loaded Backup 2 (link 1) and the world selection screen (link 2) and lastly the configuration menu I edited (link 3).

You can see the visual bug and the fact that no worlds are left. I also loaded Backup 2's original world and obviously it was a duplicate since it had the original config change. 

Can I even recover my worlds? This seems like a stupid way to have all of the stuff deleted.
 
![Rlcraft mod config world issue 1](https://github.com/gigaherz/ToolBelt/assets/91195874/f28144dd-82a9-432e-ad33-af44730aa0b0)

I
![Rlcraft mod config world issue 2](https://github.com/gigaherz/ToolBelt/assets/91195874/0a7804b7-0938-40d7-80e4-a71621739907)
![rlcraft reforge issue 3](https://github.com/gigaherz/ToolBelt/assets/91195874/6d05fb7d-f31a-4d8b-ba4d-8fc4ac5dc1e6)

**Comment by gigaherz** [comment]
I'm sorry but it is impossible for this config change to have caused the other issues, all it does is make it so all radial menu items are set to visible when displaying the menu. The value is not used anywhere else in the code. And there's no code in Tool Belt that deletes files, at all.
I do not know what actually caused this issue for you, but I would bet everything that it wasn't this config change (or Tool Belt, for that matter).
If you don't have any older backups of this world, I do not think I can help you.
