### ISSUE TITLE
Can't seem to launch the game with Toolbelts installed. 

### ISSUE THREAD

**Issue by MuteTiefling** [gigaherz/ToolBelt#143]
Testing 1.20.4 Neoforge. When I install Toolbelt, the game won't ever start. No crash or anything, it just stays on the load screen forever.

Mod Version: 1.20.4-2.0.1
Neoforge: 20.4.157

**Comment by gigaherz** [comment]
Ah did I forget to release an update... ?

**Comment by gigaherz** [comment]
Oops forgot to mention here, I released a fix. It was already coded, I just forgot to release it because Curios wasn't ready at the time.

**Comment by MuteTiefling** [comment]
Sweet, thanks for the update and the quick fix!
