### ISSUE TITLE
Toolbelt voilding items Neoforge 1.20.4

### ISSUE THREAD

**Issue by Saereth** [gigaherz/ToolBelt#145]
Original issue reported on the FTB Neotech tracker:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/5346

1. Equip a Tool Belt (mine is upgraded with 2 Belt Pouches) in the special Tool Belt slot (Shift-B)
2. Insert tools into all slots using the radial menu (hold R)
3. Save and Quit to title
4. Enter the world
5. With an empty hand, extract a tool from the belt using the radial menu
6. Put the tool back into the belt and close the menu
7. Open the radial menu again and the tool will be gone

**Comment by gigaherz** [comment]
I'm looking into it. May take a bit longer than expected because apparently the sewing kit crafting is completely broken and no one has ever told me, so I got sidetracked...

**Comment by Saereth** [comment]
Ooof, lol no worries then, I'll put a warning on the item tooltip until then just to be safe

**Comment by gigaherz** [comment]
I have been able to reproduce the issue in my development environment. I have no idea why it happens though. Will continue blinking confusedly while trying to figure this out.

**Comment by gigaherz** [comment]
It appears that performing the swap client-side, even when not in creative mode, causes the data loss issue, but removing one single line of code that only exists to hide the latency and make the mod feel more responsive, avoids the bug...
I have published an update for 1.20.4, which hopefully fixes that issue. It's currently waiting review by curseforge.
Tomorrow I will look at 1.20.1, 1.20.6 and 1.21 versions to make sure the same issue doesn't occur in those versions.

**Comment by gigaherz** [comment]
1.20.6 and 1.21 versions have been tested and do not appear to have this issue, so I'm calling it good.
