### ISSUE TITLE
1.7.10 backport?

### ISSUE THREAD

**Issue by Muramasa-** [gigaherz/ToolBelt#15]
I hate to be _that_ guy, but is there any chance you can backport this to 1.7.10?

**Comment by gigaherz** [comment]
Well there's nothing that prevents a backport, I just have no interest in doing so. And it's not just 1.7.10 at this point, I also have 0 interest in backporting to 1.8 or 1.8.9 or 1.9. In fact, chances are I won't be adding anything new to 1.10.2 or 1.11.2 anymore at this point. I just don't have that much time.

However, as I said there is no technical reason why it can't be done. The license allows anyone to fork the code and release modified versions or ports. The only thing I beg is that they don't pretend to be made by me, so I don't end up receiving the bug reports for those builds.
