### ISSUE TITLE
Toolbelt Inventory Dupe

### ISSUE THREAD

**Issue by VoidTest** [gigaherz/ToolBelt#155]
When you open toolbelt menu and craft in inventory when you shift click the output of the craft the stuff to make it don't get consumed soo if you make a portable drive fill it and then upgrade it you dupe all the stuff inside.

This was tested in ATM10

**Comment by gigaherz** [comment]
Uh oh. Will take a look.

**Comment by gigaherz** [comment]
Oops, I forgot about this. Sorry.
I have now taken a look and confirmed the issue in my development environment.
I will try to fix it asap.

**Comment by gigaherz** [comment]
Fixed as of 1.21.1-2.2.5.
