### ISSUE TITLE
Request: option for consistent slot sizes/positions in radial menu

### ISSUE THREAD

**Issue by esotericist** [gigaherz/ToolBelt#16]
One of the core usability principals behind a radial menu in most user interface design spaces is that you can develop a directional association of 'x thing is in y direction'.

Having the number and position of slots constantly shift as you add/remove items from the toolbelt makes developing this kind of association much more difficult, making it a less intuitive mod for some users.

It would be nice if there was a way to have it show all of the slots its current upgrade level has at all times, with consistent association between displayed position on the radial wheel with each storage slot in the tool belt, with the 'insert' option used for each empty slot separately.

This would allow a user to have a specific direction they associate with particular tools, and explicitly place them back in that direction without needing to care about what might be in other slots, and only need to 'relearn' directions on upgrading the belt (an infrequent event).

**Comment by gigaherz** [comment]
Hey sorry that I completely forgot about this and never released an update for 1.12. There's now a v1.9.0 out on curseforge which will probably be the last update for 1.12, unless some major bug is found in that release. enjoy!
