### ISSUE TITLE
Config option to disable anvil recipes

### ISSUE THREAD

**Issue by codetaylor** [gigaherz/ToolBelt#18]
I'm working on a pack and I have a leatherworking table from Artisans Worktables. I would like to be able to disable the default anvil recipes in order to provide my own recipes for the tool belt upgrade in the leatherworking table.

Thank you for your time. :)

**Comment by gigaherz** [comment]
I have now implemented this config option locally, whenever I finish working on the next version, it will be included.

**Comment by codetaylor** [comment]
Thank you! :)

**Comment by gigaherz** [comment]
Stuff happened and never released that next verson. THere's now a v1.9.0 up on curseforge, which includes this option. Sorry for the delay!

**Comment by codetaylor** [comment]
No worries, thank you! :)
