### ISSUE TITLE
hotkey to scroll between slot

### ISSUE THREAD

**Issue by freakone20** [gigaherz/ToolBelt#21]
i think using hotkey that will scroll between tool will be much easier especially when your tool belt had less than 5 tool?

**Comment by gigaherz** [comment]
Hey just to mention, v1.9.0 for 1.12 is up on curseforge. This includestwo hotkeys which can be used while the menu is open, to cycle clockwise/counterclockwise. They are unassigned by default, but you can bind them however you like.
