### ISSUE TITLE
[Bug] Server White/Blacklist doesn't affect players without same config alterations

### ISSUE THREAD

**Issue by Niiohontesha** [gigaherz/ToolBelt#24]
Running 
- ToolBelt-1.12.0-1.7.1
- forge-1.12.2-14.23.5.2768

I've been reading up on some of your comments and through prior conversation you make it seem as though the whitelist should allow stackable items to be placed into the toolbelt. I'm uncertain if that would break the mod, but I've been trying to add a few myself to no avail. 
Is the whitelist capable of adding stackable items, and if not, will you be implementing the capability any time soon?

**Comment by Niiohontesha** [comment]
Edit: I have changed the config in my player file to add the Toolbelt configurations and it works now.
White/blacklist settings do not affect the player unless they have the same setting. 
Blacklisting an item on the server will not blacklist it for a player.

**Comment by gigaherz** [comment]
Hey sorry that I never answered. Since forge for 1.14.x includes config sync as a feature, I decided to make use of that, meaning that only the versions on 1.14 and newer will sync the blacklist/whitelist automatically. I have no plans of implementing this on 1.12. Sorry to disappoint.
