### ISSUE TITLE
1.13.2 Server and Client both Crash when player die

### ISSUE THREAD

**Issue by Cafemocca** [gigaherz/ToolBelt#26]
[crash-2019-03-09_06.03.04-server.txt](https://github.com/gigaherz/ToolBelt/files/2947469/crash-2019-03-09_06.03.04-server.txt)

I tried on forge-1.13.2-25.0.73 and ToolBelt-1.13.2-1.8.0.
Mods are just that two.

I hope its helps you.
Thanks for nice mod :)

**Comment by gigaherz** [comment]
Thanks for the report! I'll investigate and fix asap.

**Comment by gigaherz** [comment]
This should be fixed in the latest version for 1.14.2.
