### ISSUE TITLE
The mod seems to not be able to load the mod properly

### ISSUE THREAD

**Issue by iissaacc98** [gigaherz/ToolBelt#27]
I downloaded version 1.13.2 the mod and it seemingly loaded properly, because it gave no errors, and it was is in the mod list, but when i tested it out in creative mode I could create the tool belt or find it in the search, all I could find was a lists that set which tool for the equipment in the tool belt. I don't know  if I loaded it properly or it was something from the version but may I be answered.

**Comment by gigaherz** [comment]
Thanks for the report. I'll check as soon as I get home.

**Comment by gigaherz** [comment]
hi! I'm closing this ticket since I have no intention of working on 1.13.x anymore, since 1.14 works much better. If you still have issues in 1.14.3, feel free to open a new ticket about them.
