### ISSUE TITLE
Select Item by hovering over the item in the menu when it closes

### ISSUE THREAD

**Issue by OhCreative** [gigaherz/ToolBelt#3]
So I'm using the 1.10 version of this mod, and when I open the menu, I have to click on the item to select any way you can make it to where when you release the menu hovering over an item it selects that item, or at least make it a configurable options

**Comment by gigaherz** [comment]
You mean make the "key up" for the menu act like clicking the mouse? I guess I can do that. I'll look into it.

**Comment by gigaherz** [comment]
v1.6.0 has the option to make the radial menu swap on release. It's default off, can be enabled in the ingame config menu or in the config file.
