### ISSUE TITLE
[1.14.2] Tool Belt disappears on death, with items in it.

### ISSUE THREAD

**Issue by illkerr** [gigaherz/ToolBelt#31]
Pretty much the title. I play with keepInventory and when I die tool belt is not kept after death. The item I hold the last in the tool belt remains; but all others disappear with the tool belt.

**Comment by gigaherz** [comment]
Yay, finally someone reports this. I discovered the issue last night, which apparently no one ever noticed in >650k downloads....
I'm going to release a bugfix for 1.12 "soon", but for 1.14.x, it might take some time, as I hear there's some issue with players "losing" capability data on death (it's not really lost just not properly accessible).

**Comment by illkerr** [comment]
Nice, I created a github account just to report this :D 

I really like this mod, can't wait for the fix 🤞

**Comment by gigaherz** [comment]
v1.9.5 for 1.12.2 is up on curseforge, waiting for approval. Will be here: https://minecraft.curseforge.com/projects/tool-belt/files/2730771

By the way I realized by no one had complained: the bug wasn't in the belt itself, it was in the new extra slot I added in the latest version, it never affected baubles,. :P
