### ISSUE TITLE
Doenst work on server

### ISSUE THREAD

**Issue by ErlinaEzka** [gigaherz/ToolBelt#32]
crashed the server 
MCversion 1.14.3
cant equip tool belt and cant interact with the toolbet
RMB the toolbelt will crash the server
--
Working perfectly fine on SinglePlayer 1.14.3

**Comment by gigaherz** [comment]
### OK, no need to yell though
I can read you just fine with normal font sizes.

Thanks for the report, I'm working on it and will release a bugfix as soon as I get the server working.

**Comment by gigaherz** [comment]
Err, forgot to say, I released an updatea couple hours ago, should hopefully work fine on servers. Enjoy!

**Comment by ErlinaEzka** [comment]
uhh sry... i didnt notice the font size on github...looked normal on my
screen sry m8...
