### ISSUE TITLE
Gravestone spawn is broken in multiple mods

### ISSUE THREAD

**Issue by tgstyle** [gigaherz/ToolBelt#33]
Grave spawning is broken with the latest version 1.12.2-1.9.6, I have tried with OpenBlocks and Gravestone Graves. Reverting to 1.7.1 fixes the issue.

https://gist.github.com/tgstyle/a8f8977ac7305e4fc54d12a03272032e

**Comment by gigaherz** [comment]
Thanks for the report, I'll check the mods to see if I can figure out why they fail.

**Comment by gchpaco** [comment]
I've noticed this and you can reproduce with Quark Oddities with the Totem of Holding on, and ToolBelt 1.9.6.  I speculate what's happening is that the extra slot for the belt (outside of baubles) is causing the source of the issue, but the patch I submitted doesn't solve the whole problem.

**Comment by gigaherz** [comment]
I have uploaded v1.9.8, which hopefully (🤞) fixes all these issues.

**Comment by tgstyle** [comment]
It seems to have, the graves are spawning on death now.
