### ISSUE TITLE
please remove the hard requirement for forge 21

### ISSUE THREAD

**Issue by ProsperCraft** [gigaherz/ToolBelt#35]
On the Twitch launcher forge past .16(the top one, the bottom one doesn't have sound) does not work, so I will be pushing my pack update without the update to Toolbelt as we can't launch it.

If the forge update is really required we will wait to update your mod when the launcher supports the updated forge.

https://gyazo.com/7eb2bc3b6765e71e3d8f75d4f4faec28

**Comment by gigaherz** [comment]
I can't, not without removing the recipe button which was the entire reason I made that PR to forge that was merged in update 21...

**Comment by gigaherz** [comment]
Is the issue in the twitch launcher reported to twitch/curseforge?

**Comment by ProsperCraft** [comment]
Yes, reported, by more then one of my crew.
