### ISSUE TITLE
[1.14.3] Server lockup on death in nether or end.

### ISSUE THREAD

**Issue by ProsperCraft** [gigaherz/ToolBelt#37]
It took me most of the day removing one mod at a time from the server, but I got it!!

This mod causes the server to give this stacktrace when a player dies in the nether or end-
https://gist.github.com/ProsperCraft/f179dfd208c01798afee2d0b1ec09249

Then it locks up hard.

I verified it by making it happen with only this mod, and then removed it and verified it doesn't happen with only forge.

Here is a warmroast profile of the server while it is locked up - 
https://gyazo.com/b3b2006d1f0f4e898376e1ed6957ea0b

ToolBelt-1.14.3-1.9.9
Forge - forge-1.14.3-27.0.50

**Comment by gigaherz** [comment]
oof thanks for the report, will check asap.

**Comment by ProsperCraft** [comment]
I was so confident it I had found it, so either this is a forge bug, or another mod is doing the same thing, we just had the stacktrace and lockup with a player in the end without ToolBelt in the pack.

https://gist.github.com/ProsperCraft/ec9971b73a7e60ea3b66c87d5108960c

**Comment by gigaherz** [comment]
Hmmm, this second stack trace contains 
```
 at wile.engineersdecor.ModEngineersDecor.onPlayerEvent(ModEngineersDecor.java:149) [?:1.0.9-b5] {}
```
which the first didn't have.
I don't think you can blame that mod either, though.
I notice both stack traces contain ```
at net.minecraft.world.World.func_180495_p(World.java:392) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
```
...which the mcp mappings usually call `getBlockState`. This sounds like a vanilla/forge race condition.

**Comment by oly2o6** [comment]
Also noticing this issue on a different pack, it’s todo with the dimension unloading, try using the vanilla forceload command for now, but not a permanent fix

**Comment by ProsperCraft** [comment]
@oly2o6 did you notice I produced it with only this mod, and it did not happen with forge only?

**Comment by gigaherz** [comment]
Out of curiosity, how often does it happen? Like, every time you die? every few times? rarely?

**Comment by gigaherz** [comment]
I have managed to reproduce the same crash with just forge, by dying in the nether. Closing this as not my fault. It's either forge or vanilla.

**Comment by ProsperCraft** [comment]
A little help here please talk to Lex.

https://github.com/MinecraftForge/MinecraftForge/issues/5912

**Comment by ProsperCraft** [comment]
This is still happening with 1.14.4
