### ISSUE TITLE
Crash with using Electroblob's Wizardry when player dies; World is unable to load after. 

### ISSUE THREAD

**Issue by stormbringerGT** [gigaherz/ToolBelt#39]
Having a weird crash in Minecraft 1.12.2 with Tool Belt and [Electroblob's Wizardy](https://www.curseforge.com/minecraft/mc-mods/electroblobs-wizardry) when I die. Additionally renders the world unable to be loaded.

Crash is posted here as well:
https://pastebin.com/3if6t5kQ

**Comment by stormbringerGT** [comment]
Sorry not sure how to link related bugs:
https://github.com/Electroblob77/Wizardry/issues/162

**Comment by gigaherz** [comment]
Could have sworn I fixed that issue...

**Comment by gigaherz** [comment]
Ah yes, I fixed it in 1.9.8, you seem to be using 1.9.6. See the changelog: https://www.curseforge.com/minecraft/mc-mods/tool-belt/files/2733018

**Comment by stormbringerGT** [comment]
Thank you curse forge. Lesson learned to never just hit the download button. Thanks for the quick reply!
