### ISSUE TITLE
Controls don't work

### ISSUE THREAD

**Issue by bloodconfetti** [gigaherz/ToolBelt#40]
I checked my controls to make sure I was pushing the right ones... holding V to open the tool belt inventory opens my main inventory instead, and holding R does not bring up the radial dial, nor do anything else that I can tell.

Using Forge 28.0.45, Minecraft 1.14.4, and mod version ToolBelt-1.14.4-1.10.0.

**Comment by Revvilo** [comment]
Pressing V brings up a version of your main inventory with an extra slot above your offhand slot which is where you equip the toolbelt.
Holding R will not do anything unless you have a toolbelt equipped.

**Comment by gigaherz** [comment]
Closing under the assumption bloodconfetti managed to figure out how to use the mod.
If this is not the case, we can continue troubleshooting, but chances are it's just a conflicting keybind preventing the R button from working.
