### ISSUE TITLE
Tool belt equip slot not there!

### ISSUE THREAD

**Issue by ayefff** [gigaherz/ToolBelt#43]
It showed when mod was first installed then checked inventory to equip belt and then the slot was no longer there

**Comment by gigaherz** [comment]
I'm not sure what you mean, does the "v" screen not appear? Or is the item gone from the slot?

**Comment by maxdeathman2758** [comment]
same thing the tool belt slot is never there for me at all

**Comment by yoyo199519951995** [comment]
Hey same for me here ! I have saw a screenshot with a guy who got a belt slot just above the shield one ! do i absolutly need bauble to make it work ? @gigaherz

**Comment by gigaherz** [comment]
The custom slot screen is activated with the V key by default. In case of conflicts you can change/fix the key in the controls screen of minecraft

**Comment by yoyo199519951995** [comment]
thx a lot for this information !
