### ISSUE TITLE
[1.12.2] option to disable new toolbelt menu

### ISSUE THREAD

**Issue by Shivaxi** [gigaherz/ToolBelt#47]
Since I use baubles in my modpack, I would like to disable the new menu that tool belt adds when pressing the V key, as it's just unneeded for me.  Could we get an option for that in the config?

**Comment by gigaherz** [comment]
You can set the default config of the pack to have the key unassigned.

**Comment by Shivaxi** [comment]
This is also true, I just didn't want players to be confused when they go through the controls and see that option.  Guess that'll work for now!

**Comment by gigaherz** [comment]
I'll keep this open, but I'm quite busy enough with all my 1.14 stuffs that I have going on, so no promises on implementing that option for 1.12

**Comment by Shivaxi** [comment]
actually the other issue with this is that if i have two mods that give you some kind of belt to use in the baubles belt slot, now the player can wear TWO belts, and i want to prevent this because i only want them being able to use 1 type of belt at a time

**Comment by gigaherz** [comment]
Hi! I have released v1.9.11 for 1.12.2, which adds a config option to disable accessing the custom slot (the data is preserved to avoid data loss, but is not exposed).
The config is meant for modpacks so I chose not to put it in the ingame config GUI.
