### ISSUE TITLE
ToolBelt icon appearing ingame 

### ISSUE THREAD

**Issue by S3RIAL** [gigaherz/ToolBelt#53]
**EDIT: This was the BaublesMod overlay. Customizable with NUM9. Sorry for the improper issue post**
Whilst playing RLCraft I've come across a bug which I havent seen before. The belt icon which I placed in my baubles belt slot shows up on my screen in game _(see screenshot)_

![ToolBeltBugGUI](https://user-images.githubusercontent.com/24473477/67642528-e77a8180-f90c-11e9-8a20-b59d8dd0ef82.jpg)

**Comment by gigaherz** [comment]
I have no idea what mod could possibly cause that. I do know I never experienced that in development...

Is it persistent or does it go away after restarting the game?
