### ISSUE TITLE
[1.14.4] Server Issues

### ISSUE THREAD

**Issue by NxD136** [gigaherz/ToolBelt#54]
I can't run this mod on my forge server. When I add the mod to mods folder in my server files and restart the server it just crashes. 

Any suggestions/feedback would be greatly appreciated.

Thanks,

**Comment by gigaherz** [comment]
Hi, could you post the server log so I can see where it crashes?

**Comment by NxD136** [comment]
I have figured it out, I was on the wrong forge version... Apparently your mod requires forge version 28.1.6 and higher, my server was running 28.1.0. I updated my server to the latest forge version (28.1.75) and now all works great!

You may want to specify that it requires that version or higher on curse forge, I only figured it  out cause I spent 10 mins parsing through the console... Unless you already have it posted there which in any case I did not manage to see it lol

Thanks!

- Nikolas Desforges

________________________________
