### ISSUE TITLE
Compatibility with Player Weight Mod?

### ISSUE THREAD

**Issue by Syampuuh** [gigaherz/ToolBelt#59]
Any chance you could add support for the [Player Weight mod](https://www.curseforge.com/minecraft/mc-mods/player-weight-mod)? I love this mod too much to let of it, but it can currently be used in the modpack I'm building to cheese heavier items into inventories. [According to the developer, compatibility isn't difficult to implement,](https://www.curseforge.com/minecraft/mc-mods/player-weight-mod?comment=53) but I say that completely ignorant of how either works.

**Comment by gigaherz** [comment]
Hi, I took a quick look at the API, and it does indeed seem simple enough, however, my item exposes the standard, forge-provided IItemHandler capability, so I would have expected a mod like that to support it out of the box? I would have to wonder why the author doesn't just make use of it, or provide a whitelist for items that don't need special treatment... Maybe you can get them to have this support on their end?

**Comment by Syampuuh** [comment]
🤷
I'll pass that along, thanks.

**Comment by gigaherz** [comment]
Tidying up some issues. Closing this one as "will be fixed on their end"
