### ISSUE TITLE
Can no longer assign Mouse Buttons

### ISSUE THREAD

**Issue by Ash70** [gigaherz/ToolBelt#6]
Ever since the last update (1.11.2-1.6.1) I am unable to use mouse Buttons 4/5 as the swap button; it now only seems to work with keyboard keys? When assigned to a mouse button, the ring-menu will appear briefly but close immediately again.

**Comment by gigaherz** [comment]
Hmmm, I don't recall changing anything related to that, but I will take a look as soon as I can.

**Comment by Ash70** [comment]
This may just be an issue with my mouse. I noticed today some strange bahaviour from it in other programs. I ordered a new one; arrives tomorrow. If this resolves it I will let you know.

**Comment by OhCreative** [comment]
@Ash70 Could be the drivers didn't install properly or weren't registered so button4 and button5 don't function properly! Anyways please due update!

**Comment by Ash70** [comment]
Oh yeah, it was my mouse <derp> sorry to have bothered you.
