### ISSUE TITLE
[1.15.2] "Open Belt Slot Inventory" keybind not working as intended.

### ISSUE THREAD

**Issue by K41eb** [gigaherz/ToolBelt#69]
Minecraft - 1.15.2
Forge - 31.2.0
Tool Belt - 1.2

The keybind to open the toolbelt doesn't work as intended, whatever key is assigned to it:
- the radial menu never shows up
- an alternate version of my inventory shows up instead

[Screenshots and detailed explanations of what I tried](https://imgur.com/a/agHvWXP).

The belt was generated in creative game mode.

**Comment by gigaherz** [comment]
The "belt slot inventory" **IS an alternate version of the player inventory**.
The radial menu (belt inventory) is a different keybind, defaults to R,

**Comment by K41eb** [comment]
Yup, just figured it out. For some reason the R key did nothing the first time I tried it.

What's the prupose of the alternate inventory?

**Comment by gigaherz** [comment]
It's like a mini-baubles-like feature, so you can have a belt slot to equip the belt in, even if baubles/curios is missing. You can disable it from the config if it gets in the way.
