### ISSUE TITLE
Crash on latest Forge (forge-1.12-14.21.0.2327)

### ISSUE THREAD

**Issue by Boomflex** [gigaherz/ToolBelt#7]
ToolBelt v1.6.1
Forge v2327

https://pastebin.com/Zgf7bhZ3

**Comment by gigaherz** [comment]
Yup, I'm working on it right now! ;P

**Comment by gigaherz** [comment]
Should be fixed on v1.6.2, already out on curseforge.

**Comment by Boomflex** [comment]
Hey Giga, I meant to say in my original post that I am from the All the Mods modpack dev team!

Would be great to get you across to our Discord as we are looking at adding the ToolBelt mod to the pack in the next couple of updates!

Link: https://discord.gg/gJGaabT

Thanks for fixing so quick!
