### ISSUE TITLE
[Feature Request] [1.16] Radial menu slots not shifting when an item is extracted

### ISSUE THREAD

**Issue by jasperandrew** [gigaherz/ToolBelt#73]
I think that the slot you put an item in should stay the same, whether another item has been removed or not. So, if a player wanted to always have all their tools in the same radial slot, they don't need to shuffle the tools around when they put the tools back in the belt.

So, if there are 3 slots and the player removes the tool from the top slot, the top slot should stay empty, and none of the other slots should change.

**Comment by gigaherz** [comment]
There's an option in the settings to always show empty slots

**Comment by jasperandrew** [comment]
Oh, lol. I'm dumb I guess. How do I modify the settings? I can't find any instructions.

**Comment by gigaherz** [comment]
Go to the instance folder, config, open toolbelt-client.toml in notepad, edit the file, and save.
If the game is open it *should* auto-reload the settings, but forge's auto-reload doesn't always work right.

**Comment by jasperandrew** [comment]
Awesome, thank you for your patience, I don't know how mods work lol.
