### ISSUE TITLE
Wants another mod

### ISSUE THREAD

**Issue by Firgen** [gigaherz/ToolBelt#8]
1.11.2-forge1.11.2-13.20.0.2315     ToolBelt-1.11.2-1.6.1
https://user-images.githubusercontent.com/29487700/27235550-76e13a2a-52c1-11e7-9032-2ee19641bbbf.png   it writes that it depends on another mod include following mods: but none mods are shown there and there aren´t any required mods on the page  
it isn´t even in the xml log when starting the game

**Comment by gigaherz** [comment]
I have tried loading 1.6.1 locally with forge 2315, and I don't get that crash. So unless you can provide more info that shows it really is a problem with my mod, I am going to assume it's something else in your modpack that is causing the problem.

**Comment by Firgen** [comment]
I found out later that it was caused by JEI. I downloaded a newer version of JEI and it works now. Sorry for annoying JEI crashed after I removed tool belt. Again sorry for annoying I just didn't try to start minecraft with newer jei. I feel ashamed now.  (sorry if my english is bad or weird, I am Slovak)

**Comment by gigaherz** [comment]
Don't worry I'm Spanish, your English is good compared to most people here. ;P

**Comment by Firgen** [comment]
Oh ok thanks :P
