### ISSUE TITLE
Upsizer compatibility

### ISSUE THREAD

**Issue by Yupoman** [gigaherz/ToolBelt#81]
I was wondering if it is possible for it to be compatible with this [mod](https://www.curseforge.com/minecraft/mc-mods/upsizer-mod)

I'm not looking to have a stack of tools on the belt, but by increasing the stack of tools or weapons, they can no longer be used with the belt, even if I try to put only one.

**Comment by gigaherz** [comment]
You could whitelist those tools in the config. This would allow them to be placed even if they are stacks more than 1. The check is "not stackable, unless it's in the whitelist"

**Comment by Yupoman** [comment]
Oh I thought it was just to enable new items, thank you very much!
