### ISSUE TITLE
Support Blacklisting and Whitelisting items with / (forward slash) in the name

### ISSUE THREAD

**Issue by jimurray** [gigaherz/ToolBelt#83]
I'm using ToolBelt-1.15.2-1.14.1.jar.
When playing with other mods that add items which have "/" in their name, you cannot blacklist or whitelist these items.
[The regex](https://regex101.com/r/m6SfI1/1) won't match on an item with "/" in it.
I've included a screenshot of the item I'm trying to blacklist.

![image](https://user-images.githubusercontent.com/9416640/96386930-43fd2f00-1164-11eb-9048-46643765b374.png)

**Comment by gigaherz** [comment]
Ah, huh. This is the first time I see "item folders" (so to speak) in the wild. Will fix.

**Comment by gigaherz** [comment]
Should be fixed as of ToolBelt 1.15.2 for mc1.16.3, and 1.14.2 for mc1.15.2.

**Comment by jimurray** [comment]
Awesome! Thanks for the super quick fix and release.
❤
