### ISSUE TITLE
Display belt for other players in MP

### ISSUE THREAD

**Issue by 0142929** [gigaherz/ToolBelt#9]
mod is really super cool, but is it possible to make toolbelt visible over multiplayer?
using latest ToolBelt 1.6.1 for 1.11.2

**Comment by gigaherz** [comment]
It should already work, if it doesn't it's a bug, so I'll take a look later today when I am back from work.

**Comment by 0142929** [comment]
![11](https://user-images.githubusercontent.com/896793/27471733-72ae49ee-5801-11e7-9d85-1303d8d9c402.jpg)
![22](https://user-images.githubusercontent.com/896793/27471734-72aeed18-5801-11e7-83d7-fa008359774a.jpg)

thanks :)
here are two screens of my char, one from self view and another from friend in multiplayer.

anyway, invisible toolbelt in multiplayer it is not a big problem ))
me just noticed that

**Comment by 0142929** [comment]
i realized the toolbelt is displayed in multiplayer if the toolbelt itself is in the right or left hand

**Comment by gigaherz** [comment]
That... makes quite a lot of sense! Because the server doesn't give you the entire inventory of other players, only the held items!

It also means that I can't just patch a little thing and it works -- this will require some major work.

**Comment by 0142929** [comment]
now it is clear what is the reason, so me can just pick up a toolbelt on hand to show it to a friend.
looks like problem solved.
sorry for my english.
this mod is one of my favorites :)
thank you very much!
