### ISSUE TITLE
Rendering overlay [1.17.1]

### ISSUE THREAD

**Issue by Coraline77447** [gigaherz/ToolBelt#98]
Minecraft: 1.17.1
Forge: 1.17.1, 37.0.8
ToolBelt: 1.17.0 
Crash Report: https://pastebin.com/QrzkEwq6

**Comment by gigaherz** [comment]
toolbelt 1.17.0 is incompatible with forge 37.0.8 I'll update it later this afternoon. I'm currently away from home

**Comment by gigaherz** [comment]
ToolBelt 1.17.1 should fix this error, and will be available on curseforge as soon as it's approved.

**Comment by Coraline77447** [comment]
Thanks for Fixing the error, I originally would've been able to play with ToolBelt 1.17 but was having issues with forge itself and then 37.0.8 came around which changed the rendering again (no new rendering engine but was about how models such as item or entity models are rendered was changed or somethin like that, so I thought that's what stopped ToolBelt from working during mod loading and had to temporarily uninstall ToolBelt).

**Comment by gigaherz** [comment]
Yes we (I'm part of the forge dev team) had to change the way forge allowed mods to define entity models, and that includes how mods register entity layers like the belt from ToolBelt. It was a necessary break so I made the change as soon as I found an acceptable design, to bother the least amount of modders.
