### ISSUE TITLE
new "empty slot icon" suggestion

### ISSUE THREAD

**Issue by Nika-m** [gigaherz/ToolBelt#99]
I draw it for myself, if you like it use it freely, I think it suits the mod

1. ![empty_belt_slot_background](https://user-images.githubusercontent.com/55950404/128939066-2c6a662e-593b-4a2f-98d1-dcba7307458f.png)
2. looks like this 
![image](https://user-images.githubusercontent.com/55950404/128939104-531a7472-ea73-4497-b891-ed4e70d08f71.png)

**Comment by gigaherz** [comment]
That's nice. I'll consider it. I had removed the icon from the curios slot in 1.17 because that way Curios uses the generic belt icon which is more fair to the other mods that use belts, but I'll consider it for the integrated belt slot.
